"""applications table

Revision ID: 3660e9d55275
Revises: 167ddf08ee9f
Create Date: 2021-12-26 10:39:12.974672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3660e9d55275'
down_revision = '167ddf08ee9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competition_city'), 'competition', ['city'], unique=False)
    op.create_index(op.f('ix_competition_end_date'), 'competition', ['end_date'], unique=False)
    op.create_index(op.f('ix_competition_name'), 'competition', ['name'], unique=False)
    op.create_index(op.f('ix_competition_start_date'), 'competition', ['start_date'], unique=False)
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('competition_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    op.drop_index(op.f('ix_competition_start_date'), table_name='competition')
    op.drop_index(op.f('ix_competition_name'), table_name='competition')
    op.drop_index(op.f('ix_competition_end_date'), table_name='competition')
    op.drop_index(op.f('ix_competition_city'), table_name='competition')
    op.drop_table('competition')
    # ### end Alembic commands ###
